In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv('/Users/sukitharathnayake/CodeRepo/ST4035/Data/ST 4035 Advertising.csv', index_col=0)

df.head(5)

      TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [10]:
# Fit a model to predict sales

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 1 to 200
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 7.8 KB

In [11]:
df.describe().transpose()

           count      mean        std  min     25%     50%      75%    max
TV         200.0  147.0425  85.854236  0.7  74.375  149.75  218.825  296.4
radio      200.0   23.2640  14.846809  0.0   9.975   22.90   36.525   49.6
newspaper  200.0   30.5540  21.778621  0.3  12.750   25.75   45.100  114.0
sales      200.0   14.0225   5.217457  1.6  10.375   12.90   17.400   27.0

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X = df.drop('sales', axis=1)
y = df['sales']

In [13]:
from sklearn.feature_selection import SelectFpr, f_regression

selector = SelectFpr(score_func=f_regression, alpha=0.001)  # only keeps p < 0.001
X_new = selector.fit_transform(X, y)
print("Selected:", X.columns[selector.get_support()].tolist())

Selected: ['TV', 'radio']

In [14]:
from sklearn.preprocessing import MinMaxScaler

X = df[['TV', 'radio']]
y = df['sales']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,       # 80% train, 20% test
    random_state=42      # for reproducibility
)

print(f"Train size: {X_train.shape}, Test size: {X_test.shape}")


scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train) 
X_test_scaled  = scaler.transform(X_test)

Train size: (160, 2), Test size: (40, 2)

In [15]:
model = LinearRegression()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

In [16]:
# Model evaluation

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse:.2f}')
print(f'R^2 Score: {r2:.2f}')

Mean Squared Error: 3.14
R^2 Score: 0.90

## Robust Scaling

### What is it?
Scale features using statistics that are **not sensitive to extreme values**. This Scaler removes the median and scales the data according to the quantile range, making it less sensitive to extreme values.

$$X_{scaled} = \frac{X - \text{median}}{\text{IQR}}$$

### Application
Use when your dataset has **extreme outliers**.